### PR TITLE
Updated signup.aspx to use asp.net and c#

### PR DESCRIPTION
**Pull request by cgpuglie**
Updated several elements from html to asp.net

added well commented c# to code behind to connect to database and
insert a record for a user.

This should get you guys started on the right track with migrating your
code to asp.net. Let me know if there is any part of my code you don't understand.

### CODE REVIEW

**Comment by mehrad24** [comment]
Cody,
I cant run the code because I am getting build errors for some reason. i cant figure out whats wrong And honestly i think github is fucking us up for a while now because every time we have to delete our directory and clone the z-squad because there are weird errors in github like "Binary Files differ". 
I have attached what I am seeing. 

Date: Tue, 24 Mar 2015 20:54:33 -0700

**Comment by cgpuglie** [comment]
Ryan,

I'm confused... Are you having an issue with your merge, or with executing
the code after you have merged/downloaded it?

I was able to run the code on my local machine, so if all else fails we can
forego github and I'll email you the code after work in a google doc. But,
I want to CC Dr. Clark so he can have some formal record of my contribution.

Thanks,
 _Cody G. Pugliese_
Student, Arizona State University | Computer Information Systems (BS) |
Supply Chain Management (BS) | (480) 710-7459  | Cody.Pugliese@asu.edu
cgpuglie@asu.edu

**Comment by cgpuglie** [comment]
Also, you mentioned a build error? What is the error message, the use of
HTML5 attributes in your ASP elements will likely give you some warnings,
but I didn't have any errors in my build.

Thanks,
 _Cody G. Pugliese_
Student, Arizona State University | Computer Information Systems (BS) |
Supply Chain Management (BS) | (480) 710-7459  | Cody.Pugliese@asu.edu
cgpuglie@asu.edu

**Comment by mehrad24** [comment]
I attached pictures of the errors in my last email. Take a look. 

When i try to run it is giving me an error & asking to run the last stable build.

**Comment by cgpuglie** [comment]
Downloaded the repo and found out the issue.

I downloaded a reference to a MySQL api in the project, those files aren't
included in the commit.
To add them, go to Project > Manage NuGet packages and search mysql.
Download the top result
on the page below, then the solution should work.

[image: Inline image 1]

_Cody G. Pugliese_
Student, Arizona State University | Computer Information Systems (BS) |
Supply Chain Management (BS) | (480) 710-7459  | Cody.Pugliese@asu.edu
cgpuglie@asu.edu

**Comment by mehrad24** [comment]
OK got it to work. 
Do you why our forms (login form and signup form) no longer look the same? All the CSS features/stylings are gone. The box around the form is gone, the yellow highlighting of each field only works on password, etc. 

Date: Wed, 25 Mar 2015 15:26:13 -0700

**Comment by mehrad24** [comment]
So i updated the web.config file:

```
<add key="ConnectionString" value="SERVER={https://metro704.hostmetro.com:2083/};DATABASE=bamercad_zoophy;UID={bamercad};PASSWORD={zsquad440}" />
```

I also changed ur INSERT statement because it was referring to a different table we used for the php email function. The actual table is the "user" table. 
            MySqlCommand cmd = new MySqlCommand("INSERT INTO user(lastName, firstName, email, pword, institution)"+

```
            "VALUES('"+lName.Text+"', '"+fName.Text+"', '"+email.Text+"', '"+password.Text+"', '"+institution.Text+"'));");
```

When I try to run signup page and register a user, I get an exception. See attached picture
              Date: Wed, 25 Mar 2015 15:26:13 -0700

**Comment by cgpuglie** [comment]
The connection string shouldn't have the {} still in it, those were just to
signify placeholders.

<add key="ConnectionString" value="SERVER=
https://metro704.hostmetro.com:2083/;DATABASE=bamercad_zoophy;UID=bamercad;PASSWORD=zsquad440
<https://metro704.hostmetro.com:2083/%7D;DATABASE=bamercad_zoophy;UID=%7Bbamercad%7D;PASSWORD=%7Bzsquad440>"
/>

I don't see a picture attached to the email, but I would bet that has to do
with your issue.

_Cody G. Pugliese_
Student, Arizona State University | Computer Information Systems (BS) |
Supply Chain Management (BS) | (480) 710-7459  | Cody.Pugliese@asu.edu
cgpuglie@asu.edu

**Comment by cgpuglie** [comment]
With regards to your css, the issue with the yellow highlighting was due to
a line missing from your css file. See screenshot below:
[image: Inline image 1]
I added this line, which fixed the issue.

Are you sure this has anything to do with the conversion to asp.net? I just
loaded your php version into WAMP based on my version of the repo. I'm
getting php errors and the same formatting issues that exist in the asp.net
version.
[image: Inline image 3]
This sort of leads me to believe your css got changed somewhere in your
development process. Looking at the html given to the browser by running
the php versions and the asp.net version and hitting f12 in the browser
will point you to the cause of further issues. I'm pushing a version with
the css fix.

_Cody G. Pugliese_
Student, Arizona State University | Computer Information Systems (BS) |
Supply Chain Management (BS) | (480) 710-7459  | Cody.Pugliese@asu.edu
cgpuglie@asu.edu

**Comment by cgpuglie** [comment]
Let me take a look, give me a few minutes

**Pull request merged**
